%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: smokingkids30day.csv (stored alongside this script)
%
% Auto-generated by MATLAB on 09-May-2025 16:36:29

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, 1000000];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["LGHCIndicatorName", "Geography", "Year", "Strata", "StrataName", "Denominator", "Rate", "Lower95CI", "Upper95CI", "LGHCIndicatorID", "LGHCTargetRate"];
opts.VariableTypes = ["double", "categorical", "double", "categorical", "categorical", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Geography", "Strata", "StrataName"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["LGHCIndicatorName", "Year"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["LGHCIndicatorName", "Year"], "ThousandsSeparator", ",");

% Import the data
filename = fullfile(fileparts(mfilename('fullpath')), 'smokingkids30day.csv');
smokingkids30day = readtable(filename, opts);

%% Code
averages=groupsummary(smokingkids30day, "Year", "mean", "Rate");

plot(averages.Year, averages.mean_Rate, '-o')
xlabel('Year')
ylabel('Average Smoking Rate (%)')
title('Average Smoking Rates in Kids by Year')
grid on
